/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package desktop.app;

import static java.lang.System.exit;
import java.awt.Toolkit;
import java.awt.Dimension;
import java.io.IOException;
import java.net.ConnectException;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import java.util.logging.Logger;

/**
 *
 * @author Madusha Shanaka
 */

public class Menu extends javax.swing.JFrame {
    User user = new User();
    int mousepX;
    int mousepY;
    String security_tag = "";
    public Menu() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2,size.height/2 - getHeight()/2);
        
        Taskbar.setVisible(true);
        Toolbar.setVisible(false);
        issue_card.setVisible(false);
        login.setVisible(true);
        recharge_card.setVisible(false);
        refund_card.setVisible(false);
        setting.setVisible(false);
        add_card.setVisible(false);
        //for ttesting purposes
        login_email.setText("madusha@gmail.com");
        login_password.setText("123456789");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        add_card = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        add_card_id = new javax.swing.JTextField();
        add_card_scan = new javax.swing.JButton();
        add_card_submit = new javax.swing.JButton();
        add_card_submit1 = new javax.swing.JButton();
        Taskbar = new javax.swing.JPanel();
        javax.swing.JLabel close = new javax.swing.JLabel();
        javax.swing.JLabel minimize = new javax.swing.JLabel();
        Header = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        Toolbar = new javax.swing.JPanel();
        Upeer = new javax.swing.JPanel();
        logout = new javax.swing.JLabel();
        account_setting = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        issue_card_menu = new javax.swing.JButton();
        recharge_card_menu = new javax.swing.JButton();
        refund_card_menu = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        add_remove_menue = new javax.swing.JButton();
        issue_card = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        issue_amount = new javax.swing.JTextField();
        issue_name = new javax.swing.JTextField();
        issue_card_id = new javax.swing.JTextField();
        btn_issue_scan = new javax.swing.JButton();
        btn_issue_submit = new javax.swing.JButton();
        issue_onlyno = new javax.swing.JLabel();
        recharge_card = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        recharge_amount = new javax.swing.JTextField();
        recharge_onlyno = new javax.swing.JLabel();
        recharge_card_id = new javax.swing.JTextField();
        btn_recharge_scan = new javax.swing.JButton();
        btn_recharge_submit = new javax.swing.JButton();
        login = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        login_email = new javax.swing.JTextField();
        login_password = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btn_login = new javax.swing.JButton();
        txt_error_login = new javax.swing.JLabel();
        refund_card = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        refund_card_id = new javax.swing.JTextField();
        refund_scan = new javax.swing.JButton();
        refund_submit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_refund = new javax.swing.JTextArea();
        setting = new javax.swing.JPanel();
        logout3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPasswordField3 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Card ID");

        add_card_id.setToolTipText("");

        add_card_scan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        add_card_scan.setText("Scan");
        add_card_scan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_card_scanActionPerformed(evt);
            }
        });

        add_card_submit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        add_card_submit.setText("Add");
        add_card_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_card_submitActionPerformed(evt);
            }
        });

        add_card_submit1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        add_card_submit1.setText("Remove");
        add_card_submit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_card_submit1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout add_cardLayout = new javax.swing.GroupLayout(add_card);
        add_card.setLayout(add_cardLayout);
        add_cardLayout.setHorizontalGroup(
            add_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, add_cardLayout.createSequentialGroup()
                .addContainerGap(350, Short.MAX_VALUE)
                .addComponent(add_card_submit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(add_card_submit1)
                .addGap(107, 107, 107))
            .addGroup(add_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(add_cardLayout.createSequentialGroup()
                    .addGap(78, 78, 78)
                    .addGroup(add_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(add_cardLayout.createSequentialGroup()
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(add_card_id, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(add_cardLayout.createSequentialGroup()
                            .addGap(273, 273, 273)
                            .addComponent(add_card_scan)))
                    .addContainerGap(107, Short.MAX_VALUE)))
        );
        add_cardLayout.setVerticalGroup(
            add_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, add_cardLayout.createSequentialGroup()
                .addContainerGap(324, Short.MAX_VALUE)
                .addGroup(add_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_card_submit)
                    .addComponent(add_card_submit1))
                .addGap(226, 226, 226))
            .addGroup(add_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(add_cardLayout.createSequentialGroup()
                    .addGap(226, 226, 226)
                    .addGroup(add_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(add_card_id, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(add_card_scan)
                    .addContainerGap(283, Short.MAX_VALUE)))
        );

        Taskbar.setBackground(new java.awt.Color(153, 153, 153));
        Taskbar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                TaskbarMouseDragged(evt);
            }
        });
        Taskbar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TaskbarMousePressed(evt);
            }
        });

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/close.png"))); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });

        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Minimize_Box_Blue.png"))); // NOI18N
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });

        Header.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Header.setText("Smart Payment System");

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/money.png"))); // NOI18N

        javax.swing.GroupLayout TaskbarLayout = new javax.swing.GroupLayout(Taskbar);
        Taskbar.setLayout(TaskbarLayout);
        TaskbarLayout.setHorizontalGroup(
            TaskbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TaskbarLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(icon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
        );
        TaskbarLayout.setVerticalGroup(
            TaskbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(minimize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(close, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(TaskbarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TaskbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(icon)
                    .addComponent(Header))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Toolbar.setBackground(new java.awt.Color(39, 39, 39));

        Upeer.setBackground(new java.awt.Color(39, 39, 39));
        Upeer.setPreferredSize(new java.awt.Dimension(240, 40));

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout.png"))); // NOI18N
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });

        account_setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Settings.png"))); // NOI18N
        account_setting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                account_settingMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout UpeerLayout = new javax.swing.GroupLayout(Upeer);
        Upeer.setLayout(UpeerLayout);
        UpeerLayout.setHorizontalGroup(
            UpeerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpeerLayout.createSequentialGroup()
                .addContainerGap(169, Short.MAX_VALUE)
                .addComponent(account_setting)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logout))
        );
        UpeerLayout.setVerticalGroup(
            UpeerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpeerLayout.createSequentialGroup()
                .addGroup(UpeerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logout)
                    .addComponent(account_setting))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        Toolbar.add(Upeer);

        jPanel1.setBackground(new java.awt.Color(39, 39, 39));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 71, Short.MAX_VALUE)
        );

        Toolbar.add(jPanel1);

        issue_card_menu.setBackground(new java.awt.Color(255, 255, 255));
        issue_card_menu.setForeground(new java.awt.Color(255, 255, 255));
        issue_card_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/default_menu.png"))); // NOI18N
        issue_card_menu.setText("Issue Card");
        issue_card_menu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        issue_card_menu.setPreferredSize(new java.awt.Dimension(240, 50));
        issue_card_menu.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hover_menu.png"))); // NOI18N
        issue_card_menu.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/seleted_menu.png"))); // NOI18N
        issue_card_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                issue_card_menuMouseClicked(evt);
            }
        });
        issue_card_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issue_card_menuActionPerformed(evt);
            }
        });
        Toolbar.add(issue_card_menu);

        recharge_card_menu.setForeground(new java.awt.Color(255, 255, 255));
        recharge_card_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/default_menu.png"))); // NOI18N
        recharge_card_menu.setText("Recharge Card");
        recharge_card_menu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        recharge_card_menu.setPreferredSize(new java.awt.Dimension(240, 50));
        recharge_card_menu.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hover_menu.png"))); // NOI18N
        recharge_card_menu.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/seleted_menu.png"))); // NOI18N
        recharge_card_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recharge_card_menuMouseClicked(evt);
            }
        });
        recharge_card_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recharge_card_menuActionPerformed(evt);
            }
        });
        Toolbar.add(recharge_card_menu);

        refund_card_menu.setBackground(new java.awt.Color(39, 39, 39));
        refund_card_menu.setForeground(new java.awt.Color(255, 255, 255));
        refund_card_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/default_menu.png"))); // NOI18N
        refund_card_menu.setText("Refund Card");
        refund_card_menu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        refund_card_menu.setPreferredSize(new java.awt.Dimension(240, 50));
        refund_card_menu.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hover_menu.png"))); // NOI18N
        refund_card_menu.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/seleted_menu.png"))); // NOI18N
        refund_card_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refund_card_menuMouseClicked(evt);
            }
        });
        refund_card_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refund_card_menuActionPerformed(evt);
            }
        });
        Toolbar.add(refund_card_menu);

        jPanel3.setBackground(new java.awt.Color(39, 39, 39));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        Toolbar.add(jPanel3);

        add_remove_menue.setForeground(new java.awt.Color(255, 255, 255));
        add_remove_menue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/default_menu.png"))); // NOI18N
        add_remove_menue.setText("Add/Remove Card");
        add_remove_menue.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add_remove_menue.setPreferredSize(new java.awt.Dimension(240, 50));
        add_remove_menue.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hover_menu.png"))); // NOI18N
        add_remove_menue.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/seleted_menu.png"))); // NOI18N
        add_remove_menue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_remove_menueMouseClicked(evt);
            }
        });
        Toolbar.add(add_remove_menue);

        issue_card.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Customer Name");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Amount (LKR)");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Card ID");

        issue_amount.setToolTipText("");
        issue_amount.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                issue_amountComponentAdded(evt);
            }
        });
        issue_amount.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                issue_amountInputMethodTextChanged(evt);
            }
        });
        issue_amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issue_amountActionPerformed(evt);
            }
        });
        issue_amount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                issue_amountKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                issue_amountKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                issue_amountKeyTyped(evt);
            }
        });

        issue_name.setToolTipText("");

        issue_card_id.setEditable(false);
        issue_card_id.setToolTipText("");

        btn_issue_scan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_issue_scan.setText("Scan");
        btn_issue_scan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_issue_scanActionPerformed(evt);
            }
        });

        btn_issue_submit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_issue_submit.setText("Submit");
        btn_issue_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_issue_submitActionPerformed(evt);
            }
        });

        issue_onlyno.setForeground(new java.awt.Color(255, 0, 0));
        issue_onlyno.setText("You can enter numbers only!");

        javax.swing.GroupLayout issue_cardLayout = new javax.swing.GroupLayout(issue_card);
        issue_card.setLayout(issue_cardLayout);
        issue_cardLayout.setHorizontalGroup(
            issue_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(issue_cardLayout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addGroup(issue_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, issue_cardLayout.createSequentialGroup()
                        .addComponent(btn_issue_submit)
                        .addGap(76, 76, 76))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, issue_cardLayout.createSequentialGroup()
                        .addGroup(issue_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(issue_cardLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(issue_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(issue_onlyno, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(issue_card_id, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(issue_cardLayout.createSequentialGroup()
                                .addGap(275, 275, 275)
                                .addComponent(btn_issue_scan))
                            .addGroup(issue_cardLayout.createSequentialGroup()
                                .addGroup(issue_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(issue_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(issue_name, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                                    .addComponent(issue_amount))))
                        .addGap(105, 105, 105))))
        );
        issue_cardLayout.setVerticalGroup(
            issue_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(issue_cardLayout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addGroup(issue_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(issue_cardLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(issue_name)
                        .addGap(40, 40, 40))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(issue_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(issue_amount, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addGap(14, 14, 14)
                .addComponent(issue_onlyno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(issue_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(issue_card_id, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_issue_scan)
                .addGap(26, 26, 26)
                .addComponent(btn_issue_submit)
                .addGap(128, 128, 128))
        );

        recharge_card.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Card ID");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Amount (LKR)");

        recharge_amount.setToolTipText("");
        recharge_amount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                recharge_amountKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                recharge_amountKeyTyped(evt);
            }
        });

        recharge_onlyno.setForeground(new java.awt.Color(255, 0, 0));
        recharge_onlyno.setText("You can enter numbers only!");

        recharge_card_id.setEditable(false);
        recharge_card_id.setToolTipText("");

        btn_recharge_scan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_recharge_scan.setText("Scan");
        btn_recharge_scan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_recharge_scanActionPerformed(evt);
            }
        });

        btn_recharge_submit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_recharge_submit.setText("Submit");
        btn_recharge_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_recharge_submitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout recharge_cardLayout = new javax.swing.GroupLayout(recharge_card);
        recharge_card.setLayout(recharge_cardLayout);
        recharge_cardLayout.setHorizontalGroup(
            recharge_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, recharge_cardLayout.createSequentialGroup()
                .addContainerGap(265, Short.MAX_VALUE)
                .addGroup(recharge_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(recharge_card_id, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(recharge_onlyno, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(recharge_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(99, 99, 99))
            .addGroup(recharge_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(recharge_cardLayout.createSequentialGroup()
                    .addGap(74, 74, 74)
                    .addGroup(recharge_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btn_recharge_submit, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, recharge_cardLayout.createSequentialGroup()
                            .addGroup(recharge_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(recharge_cardLayout.createSequentialGroup()
                                    .addGap(275, 275, 275)
                                    .addComponent(btn_recharge_scan))
                                .addGroup(recharge_cardLayout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(151, 151, 151)))
                    .addContainerGap(78, Short.MAX_VALUE)))
        );
        recharge_cardLayout.setVerticalGroup(
            recharge_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recharge_cardLayout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(recharge_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(recharge_onlyno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(recharge_card_id, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(recharge_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(recharge_cardLayout.createSequentialGroup()
                    .addGap(186, 186, 186)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(44, 44, 44)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(btn_recharge_scan)
                    .addGap(26, 26, 26)
                    .addComponent(btn_recharge_submit)
                    .addGap(187, 187, 187)))
        );

        login.setBackground(new java.awt.Color(255, 255, 255));
        login.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        login.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Email");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Password");

        login_email.setBorder(null);
        login_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_emailActionPerformed(evt);
            }
        });

        login_password.setToolTipText("");
        login_password.setBorder(null);
        login_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_passwordActionPerformed(evt);
            }
        });

        btn_login.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_login.setText("Login");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });

        txt_error_login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout loginLayout = new javax.swing.GroupLayout(login);
        login.setLayout(loginLayout);
        loginLayout.setHorizontalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(loginLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(login_email, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                            .addComponent(jSeparator1)))
                    .addComponent(jLabel1)
                    .addGroup(loginLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(38, 38, 38)
                        .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_error_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(login_password)
                            .addComponent(jSeparator2))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginLayout.createSequentialGroup()
                .addContainerGap(435, Short.MAX_VALUE)
                .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(371, 371, 371))
        );
        loginLayout.setVerticalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addContainerGap(223, Short.MAX_VALUE)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(login_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(login_password))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_error_login)
                .addGap(26, 26, 26)
                .addComponent(btn_login)
                .addGap(158, 158, 158))
        );

        refund_card.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Card ID");

        refund_card_id.setEditable(false);
        refund_card_id.setToolTipText("");

        refund_scan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        refund_scan.setText("Scan");
        refund_scan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refund_scanActionPerformed(evt);
            }
        });

        refund_submit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        refund_submit.setText("Submit");
        refund_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refund_submitActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        txt_refund.setBackground(new java.awt.Color(240, 240, 240));
        txt_refund.setColumns(20);
        txt_refund.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        txt_refund.setRows(5);
        jScrollPane1.setViewportView(txt_refund);

        javax.swing.GroupLayout refund_cardLayout = new javax.swing.GroupLayout(refund_card);
        refund_card.setLayout(refund_cardLayout);
        refund_cardLayout.setHorizontalGroup(
            refund_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, refund_cardLayout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addGroup(refund_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(refund_submit, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, refund_cardLayout.createSequentialGroup()
                        .addGroup(refund_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(refund_cardLayout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(refund_card_id, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(refund_cardLayout.createSequentialGroup()
                                .addGap(273, 273, 273)
                                .addComponent(refund_scan)))
                        .addGap(29, 29, 29)))
                .addGap(75, 75, 75))
            .addGroup(refund_cardLayout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        refund_cardLayout.setVerticalGroup(
            refund_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(refund_cardLayout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addGroup(refund_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refund_card_id, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(refund_scan)
                .addGap(26, 26, 26)
                .addComponent(refund_submit)
                .addGap(65, 65, 65)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        setting.setBackground(new java.awt.Color(255, 255, 255));
        setting.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setting.setForeground(new java.awt.Color(255, 255, 255));

        logout3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/home1.png"))); // NOI18N
        logout3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout3MouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Change the email");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Change the password");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Old email");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Confirm new email");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("New email");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Old passwrod");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("New passwrod");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Confirm new passwrod");

        jButton1.setText("Change password");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton5.setText("Change email");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout settingLayout = new javax.swing.GroupLayout(setting);
        setting.setLayout(settingLayout);
        settingLayout.setHorizontalGroup(
            settingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingLayout.createSequentialGroup()
                .addGroup(settingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(settingLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logout3))
                    .addGroup(settingLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel9))
                    .addGroup(settingLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(settingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(settingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addGroup(settingLayout.createSequentialGroup()
                                    .addGap(53, 53, 53)
                                    .addGroup(settingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButton1)
                                        .addGroup(settingLayout.createSequentialGroup()
                                            .addGroup(settingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel15)
                                                .addComponent(jLabel14)
                                                .addComponent(jLabel16))
                                            .addGap(423, 423, 423)))))
                            .addGroup(settingLayout.createSequentialGroup()
                                .addGroup(settingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addGap(30, 30, 30)
                                .addGroup(settingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField1)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
                                    .addComponent(jPasswordField1)
                                    .addComponent(jPasswordField2)
                                    .addComponent(jPasswordField3)))
                            .addComponent(jButton5))))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        settingLayout.setVerticalGroup(
            settingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logout3)
                .addGap(41, 41, 41)
                .addComponent(jLabel9)
                .addGap(21, 21, 21)
                .addGroup(settingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(settingLayout.createSequentialGroup()
                        .addGroup(settingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(settingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12))
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jButton5)
                .addGap(25, 25, 25)
                .addComponent(jLabel10)
                .addGap(29, 29, 29)
                .addGroup(settingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(settingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(settingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jPasswordField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jButton1)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Taskbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(login, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(Toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 643, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 192, Short.MAX_VALUE)
                    .addComponent(issue_card, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 258, Short.MAX_VALUE)
                    .addComponent(recharge_card, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 258, Short.MAX_VALUE)
                    .addComponent(refund_card, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(setting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 260, Short.MAX_VALUE)
                    .addComponent(add_card, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Taskbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 56, Short.MAX_VALUE)
                    .addComponent(Toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(issue_card, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 55, Short.MAX_VALUE)
                    .addComponent(recharge_card, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 59, Short.MAX_VALUE)
                    .addComponent(refund_card, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 51, Short.MAX_VALUE)
                    .addComponent(setting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 50, Short.MAX_VALUE)
                    .addComponent(add_card, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void TaskbarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TaskbarMouseDragged
        int cordinateX = evt.getXOnScreen();
        int cordinateY = evt.getYOnScreen();
        this.setLocation(cordinateX-mousepX, cordinateY-mousepY);
    }//GEN-LAST:event_TaskbarMouseDragged

    private void TaskbarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TaskbarMousePressed
        mousepX = evt.getX();
        mousepY = evt.getY();
    }//GEN-LAST:event_TaskbarMousePressed

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        this.setExtendedState(Menu.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        txt_error_login.setText("");
        try {
            if((!("".equals(login_email.getText()))) && (!("".equals(login_password.getText())))){
                int val = 2; //Co0nnection failed
                try{
                   val = User.login(login_email.getText(),login_password.getText());
                }catch (Exception e) {
                    e.printStackTrace();
                }
                if(val == 1){
                    Toolbar.setVisible(true);
                    issue_card.setVisible(true);
                    login.setVisible(false);
                    recharge_card.setVisible(false);
                    refund_card.setVisible(false);
                    setting.setVisible(false);
                    add_card.setVisible(false);
                    issue_onlyno.setVisible(false);
                    recharge_onlyno.setVisible(false);
                }else if (val == 0){
                    txt_error_login.setText("Invalid email or password");
                }else if(val == 2){
                    JOptionPane.showMessageDialog(null, "Server Connection failed", "Message", JOptionPane.ERROR_MESSAGE);
                }else{
                    JOptionPane.showMessageDialog(null, "Something went wrong", "Message", JOptionPane.ERROR_MESSAGE);
                }
            }else{
                txt_error_login.setText("Email or password can't be empty");
            }
        }catch (Exception e) {
            e.printStackTrace();
       }
    }//GEN-LAST:event_btn_loginActionPerformed

    private void login_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_login_passwordActionPerformed

    private void refund_card_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refund_card_menuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refund_card_menuActionPerformed

    private void issue_amountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_issue_amountKeyPressed
        
    }//GEN-LAST:event_issue_amountKeyPressed

    private void issue_amountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_issue_amountKeyTyped

    }//GEN-LAST:event_issue_amountKeyTyped

    private void btn_issue_scanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_issue_scanActionPerformed
        try {
            issue_card_id.setText("");
            Reader rdr = new Reader();
            String tmp = rdr.getID();
            security_tag = tmp.substring(0,16);
            issue_card_id.setText(tmp.substring(18,26));
        } catch (Exception ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_issue_scanActionPerformed

    private void btn_issue_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_issue_submitActionPerformed
        if(!(issue_name.getText().equals(""))){
            if(!(issue_amount.getText().equals("")) && !(issue_onlyno.isVisible())){
                if(!(issue_card_id.getText().equals(""))){
                    int val = 0;
                    int i = Integer.parseInt(issue_amount.getText());
                    try{
                        val = User.issue_card(issue_name.getText(), i, issue_card_id.getText(), User.id,security_tag);
                    }catch (Exception e) {
                            e.printStackTrace();
                    }
                    switch (val) {
                        case 1:
                            JOptionPane.showMessageDialog(null, "Card is ready to issue", "Message", JOptionPane.INFORMATION_MESSAGE);
                            issue_amount.setText("");
                            issue_name.setText("");
                            issue_card_id.setText("");
                            security_tag = "";
                            break;
                        case 2:
                            JOptionPane.showMessageDialog(null, "Sorry! Card is not exist", "Error", JOptionPane.WARNING_MESSAGE);
                            break;
                        default:
                            JOptionPane.showMessageDialog(null, "Some thing went wrong", "Error", JOptionPane.ERROR_MESSAGE);
                            break;
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Please scan the card", "Message", JOptionPane.ERROR_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(null, "Please enter the valid amount in LKR", "Message", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Please enter the customer's name", "Message", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btn_issue_submitActionPerformed

    private void recharge_amountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_recharge_amountKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_recharge_amountKeyPressed

    private void recharge_amountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_recharge_amountKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_recharge_amountKeyTyped

    private void btn_recharge_scanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_recharge_scanActionPerformed
        try {
            recharge_card_id.setText("");
            Reader rdr = new Reader();
            recharge_card_id.setText(rdr.getID());
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_recharge_scanActionPerformed

    private void btn_recharge_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_recharge_submitActionPerformed
        try{
            if(!(recharge_amount.getText().equals("") || recharge_card_id.getText().equals(""))){
                int i = Integer.parseInt(recharge_amount.getText());
                JOptionPane.showMessageDialog(null, "Card Updated Succcessfully", "Message", JOptionPane.INFORMATION_MESSAGE);
                recharge_amount.setText("");
                recharge_card_id.setText("");
                recharge_onlyno.setVisible(false);
            }
        }catch(Exception e){

        }
    }//GEN-LAST:event_btn_recharge_submitActionPerformed

    private void refund_scanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refund_scanActionPerformed
        try {
            txt_refund.setText("");  
            refund_card_id.setText("");
            Reader rdr = new Reader();
            refund_card_id.setText(rdr.getID());
                  
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_refund_scanActionPerformed

    private void refund_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refund_submitActionPerformed
        if(!(refund_card_id.getText().equals(""))){
            if(refund_card_id.getText().length()>3){
                int val = 0;
                try{
                    val = User.refundCard(add_card_id.getText());
                }catch (Exception e) {
                        e.printStackTrace();
                }
                switch (val) {
                    case 1:
                        txt_refund.setText("Card refunded successfully!\n" + "--------------------------\n" + " Card Balance   -  Rs.170");
                        break;
                    case 2:
                        JOptionPane.showMessageDialog(null, "Sorry! Card is not exist", "Error", JOptionPane.WARNING_MESSAGE);
                        break;
                    case 3:
                        JOptionPane.showMessageDialog(null, "Card is not issued yet", "Error", JOptionPane.WARNING_MESSAGE);
                        break;
                    default:
                        JOptionPane.showMessageDialog(null, "Some thing went wrong", "Error", JOptionPane.ERROR_MESSAGE);
                        break;
                }
                
            }else{
                JOptionPane.showMessageDialog(null, "Card ID must contains minimum 4 4 characters", "Message", JOptionPane.ERROR_MESSAGE);
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "Please enter the card ID", "Message", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_refund_submitActionPerformed

    private void issue_card_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_issue_card_menuMouseClicked
        Toolbar.setVisible(true);
        issue_card.setVisible(true);
        login.setVisible(false);
        recharge_card.setVisible(false);
        refund_card.setVisible(false);
        setting.setVisible(false);
        add_card.setVisible(false);
    }//GEN-LAST:event_issue_card_menuMouseClicked

    private void recharge_card_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recharge_card_menuMouseClicked
        Toolbar.setVisible(true);
        issue_card.setVisible(false);
        login.setVisible(false);
        recharge_card.setVisible(true);
        refund_card.setVisible(false);
        setting.setVisible(false);
        add_card.setVisible(false);
    }//GEN-LAST:event_recharge_card_menuMouseClicked

    private void refund_card_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refund_card_menuMouseClicked
        Toolbar.setVisible(true);
        issue_card.setVisible(false);
        login.setVisible(false);
        recharge_card.setVisible(false);
        refund_card.setVisible(true);
        setting.setVisible(false);
        add_card.setVisible(false);
    }//GEN-LAST:event_refund_card_menuMouseClicked

    private void issue_card_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issue_card_menuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_issue_card_menuActionPerformed

    private void account_settingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_account_settingMouseClicked
        Toolbar.setVisible(false);
        issue_card.setVisible(false);
        login.setVisible(false);
        recharge_card.setVisible(false);
        refund_card.setVisible(false);
        setting.setVisible(true);
        add_card.setVisible(false);
    }//GEN-LAST:event_account_settingMouseClicked

    private void logout3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout3MouseClicked
        Toolbar.setVisible(true);
        issue_card.setVisible(true);
        login.setVisible(false);
        recharge_card.setVisible(false);
        refund_card.setVisible(false);
        setting.setVisible(false);
        add_card.setVisible(false);
    }//GEN-LAST:event_logout3MouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        User.token = "";
        User.id = "";
        User.name = "";
        Toolbar.setVisible(false);
        issue_card.setVisible(false);
        login.setVisible(true);
        recharge_card.setVisible(false);
        refund_card.setVisible(false);
        setting.setVisible(false);
        add_card.setVisible(false);
        login_email.setText("");
        login_password.setText("");
    }//GEN-LAST:event_logoutMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JOptionPane.showMessageDialog(null, "Password Updated Succcessfully", "Message", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        JOptionPane.showMessageDialog(null, "Email Updated Succcessfully", "Message", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void add_remove_menueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_remove_menueMouseClicked
        Toolbar.setVisible(true);
        issue_card.setVisible(false);
        login.setVisible(false);
        recharge_card.setVisible(false);
        refund_card.setVisible(false);
        setting.setVisible(false);
        add_card.setVisible(true);
    }//GEN-LAST:event_add_remove_menueMouseClicked

    private void add_card_scanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_card_scanActionPerformed
        try {
            add_card_id.setText("");
            Reader rdr = new Reader();
            add_card_id.setText(rdr.getID());
                  
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_add_card_scanActionPerformed

    private void add_card_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_card_submitActionPerformed
        
        if(!(add_card_id.getText().equals(""))){
            if(add_card_id.getText().length()>3){
                int val = 0;
                try{
                    val = User.addCard(add_card_id.getText());
                }catch (Exception e) {
                        e.printStackTrace();
                }
                switch (val) {
                    case 1:
                        JOptionPane.showMessageDialog(null, "Card added Succcessfully", "Message", JOptionPane.INFORMATION_MESSAGE);
                        add_card_id.setText("");
                        break;
                    case 2:
                        JOptionPane.showMessageDialog(null, "Sorry! Card is already added", "Error", JOptionPane.WARNING_MESSAGE);
                        break;
                    default:
                        JOptionPane.showMessageDialog(null, "Some thing went wrong", "Error", JOptionPane.ERROR_MESSAGE);
                        break;
                }
            }else{
                JOptionPane.showMessageDialog(null, "Card ID must contains minimum 4 characters", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Please enter the card ID", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_add_card_submitActionPerformed

    private void add_card_submit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_card_submit1ActionPerformed
        if(!(add_card_id.getText().equals(""))){
            if(add_card_id.getText().length()>3){
                int val = 0;
                try{
                    val = User.deleteCard(add_card_id.getText());
                }catch (Exception e) {
                        e.printStackTrace();
                }
                switch (val) {
                    case 1:
                        JOptionPane.showMessageDialog(null, "Card removed Succcessfully", "Message", JOptionPane.INFORMATION_MESSAGE);
                        add_card_id.setText("");
                        break;
                    case 2:
                        JOptionPane.showMessageDialog(null, "Sorry! Card is not exist", "Error", JOptionPane.WARNING_MESSAGE);
                        break;
                    default:
                        JOptionPane.showMessageDialog(null, "Some thing went wrong", "Error", JOptionPane.ERROR_MESSAGE);
                        break;
                }
            }else{
                JOptionPane.showMessageDialog(null, "Card ID must contains minimum 4 characters", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Please enter the card ID", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_add_card_submit1ActionPerformed

    private void login_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_login_emailActionPerformed

    private void issue_amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issue_amountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_issue_amountActionPerformed

    private void issue_amountComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_issue_amountComponentAdded
        
    }//GEN-LAST:event_issue_amountComponentAdded

    private void issue_amountInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_issue_amountInputMethodTextChanged

    }//GEN-LAST:event_issue_amountInputMethodTextChanged

    private void issue_amountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_issue_amountKeyReleased
        try{
            int i = Integer.parseInt(issue_amount.getText());
            issue_onlyno.setVisible(false);
        }catch(Exception e){
            issue_onlyno.setVisible(true);
        }
    }//GEN-LAST:event_issue_amountKeyReleased

    private void recharge_card_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recharge_card_menuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recharge_card_menuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Header;
    private javax.swing.JPanel Taskbar;
    private javax.swing.JPanel Toolbar;
    private javax.swing.JPanel Upeer;
    private javax.swing.JLabel account_setting;
    private javax.swing.JPanel add_card;
    private javax.swing.JTextField add_card_id;
    private javax.swing.JButton add_card_scan;
    private javax.swing.JButton add_card_submit;
    private javax.swing.JButton add_card_submit1;
    private javax.swing.JButton add_remove_menue;
    private javax.swing.JButton btn_issue_scan;
    private javax.swing.JButton btn_issue_submit;
    private javax.swing.JButton btn_login;
    private javax.swing.JButton btn_recharge_scan;
    private javax.swing.JButton btn_recharge_submit;
    private javax.swing.JLabel icon;
    private javax.swing.JTextField issue_amount;
    private javax.swing.JPanel issue_card;
    private javax.swing.JTextField issue_card_id;
    private javax.swing.JButton issue_card_menu;
    private javax.swing.JTextField issue_name;
    private javax.swing.JLabel issue_onlyno;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JPanel login;
    private javax.swing.JTextField login_email;
    private javax.swing.JPasswordField login_password;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel logout3;
    private javax.swing.JTextField recharge_amount;
    private javax.swing.JPanel recharge_card;
    private javax.swing.JTextField recharge_card_id;
    private javax.swing.JButton recharge_card_menu;
    private javax.swing.JLabel recharge_onlyno;
    private javax.swing.JPanel refund_card;
    private javax.swing.JTextField refund_card_id;
    private javax.swing.JButton refund_card_menu;
    private javax.swing.JButton refund_scan;
    private javax.swing.JButton refund_submit;
    private javax.swing.JPanel setting;
    private javax.swing.JLabel txt_error_login;
    private javax.swing.JTextArea txt_refund;
    // End of variables declaration//GEN-END:variables
}
