/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import java.util.concurrent.TimeUnit;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author Madusha Shanaka
 */
public class Menu extends javax.swing.JFrame {
    
    public static String id = "";
    public static String token = "admin2021";
    public static Employer emp[] = new Employer[5];
    public static int emp_count=3;
    public Menu() {
        //emp[0]= new Employer();
        //emp[0].setData("Saman@gmail.com", "saman123", "976458223V", false);
        //emp[1].setData("Kamal@gmail.com", "kamal123", "986452335V", true);
        //emp[2].setData("Madusha@gmail.com", "madusha123", "973131559V", true);
        
        initComponents();
        Edit.setVisible(false);
        Option.setVisible(false);
        btn_delete.setVisible(false);
        
        //email.setText("madusha@gmail.com");
        //pward.setText("madusha123");
        txt_onlyno.setVisible(false);
    }
    
    private boolean isadmin(String token){
        //return(token.contains("admin"));
        if (email.getText().equals("madusha@gmail.com") && pward.getText().equals("madusha123")){
            return true;
        }
        if (email.getText().equals("shanaka@gmail.com") && pward.getText().equals("shanaka123")){
            return false;
        }
        return false;
    }
    
    private boolean login_success(String token){
        /*try {
            //login_check lgin = new login_check();
            //lgin.call_me(email.getText(),pward.getText());
        }catch (Exception e) {
            e.printStackTrace();
       }
        return(!("".equals(token)));*/
        if (email.getText().equals("madusha@gmail.com") && pward.getText().equals("madusha123")){
            return true;
        }
        if (email.getText().equals("shanaka@gmail.com") && pward.getText().equals("shanaka123")){
            return true;
        }
        txt_error_login.setText("Invalid username or passward");
        return false;
    }
    
    private boolean card_issue_success(String token){
        try {
            issue_card issue = new issue_card();
            //issue.call_me(email.getText(),pward.getText());
        }catch (Exception e) {
            e.printStackTrace();
       }
        return(!("".equals(token)));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        panel_login = new javax.swing.JPanel();
        btn_login = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        txt_error_login = new javax.swing.JLabel();
        pward = new javax.swing.JPasswordField();
        panel_issue_card = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_amount = new javax.swing.JTextField();
        txt_customer_name = new javax.swing.JTextField();
        txt_card_id = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        txt_onlyno = new javax.swing.JLabel();
        panel_add = new javax.swing.JPanel();
        btn_back_add = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txt_fname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_nic = new javax.swing.JTextField();
        btn_save = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        is_admin = new javax.swing.JCheckBox();
        jLabel17 = new javax.swing.JLabel();
        txt_pward = new javax.swing.JPasswordField();
        txt_lname = new javax.swing.JTextField();
        panel_edit_email = new javax.swing.JPanel();
        btn_back_edit = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txt_oldemail = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_newemail = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_newemail1 = new javax.swing.JTextField();
        btn_edit = new javax.swing.JButton();
        panel_search = new javax.swing.JPanel();
        btn_back_search = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btn_sear = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        btn_delete = new javax.swing.JButton();
        txt_search_result = new javax.swing.JLabel();
        txt_mails = new javax.swing.JTextField();
        txt_nicno = new javax.swing.JTextField();
        panel_menu = new javax.swing.JPanel();
        btn_addcustomer = new javax.swing.JButton();
        btn_issue = new javax.swing.JButton();
        btn_search = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        panel_edit_passward = new javax.swing.JPanel();
        btn_back_edit1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        btn_edit1 = new javax.swing.JButton();
        txt_oldpassward = new javax.swing.JPasswordField();
        txt_newpassward = new javax.swing.JPasswordField();
        txt_newpassward1 = new javax.swing.JPasswordField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        javax.swing.JMenuItem logout = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenuItem();
        Edit = new javax.swing.JMenu();
        edit_email = new javax.swing.JMenuItem();
        edit_passward = new javax.swing.JMenuItem();
        Option = new javax.swing.JMenu();
        javax.swing.JMenuItem add_emp = new javax.swing.JMenuItem();
        remove_emp = new javax.swing.JMenuItem();
        search_emp = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Smart Paying");
        setName("menu"); // NOI18N

        jLayeredPane1.setLayout(new java.awt.CardLayout());

        btn_login.setText("Login");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Email");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Passward");

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_loginLayout = new javax.swing.GroupLayout(panel_login);
        panel_login.setLayout(panel_loginLayout);
        panel_loginLayout.setHorizontalGroup(
            panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_loginLayout.createSequentialGroup()
                .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_loginLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(45, 45, 45)
                        .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_error_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panel_loginLayout.createSequentialGroup()
                                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(pward)))
                    .addGroup(panel_loginLayout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(btn_login)))
                .addGap(68, 68, 68))
        );
        panel_loginLayout.setVerticalGroup(
            panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_loginLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pward, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(txt_error_login)
                .addGap(31, 31, 31)
                .addComponent(btn_login)
                .addContainerGap(158, Short.MAX_VALUE))
        );

        jLayeredPane1.add(panel_login, "card2");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Customer Name");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Amount (LKR)");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Card ID");

        txt_amount.setToolTipText("");
        txt_amount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_amountKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_amountKeyTyped(evt);
            }
        });

        txt_customer_name.setToolTipText("");

        txt_card_id.setToolTipText("");

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton7.setText("Scan");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton8.setText("Submit");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        txt_onlyno.setForeground(new java.awt.Color(255, 0, 0));
        txt_onlyno.setText("You can enter numbers only!");

        javax.swing.GroupLayout panel_issue_cardLayout = new javax.swing.GroupLayout(panel_issue_card);
        panel_issue_card.setLayout(panel_issue_cardLayout);
        panel_issue_cardLayout.setHorizontalGroup(
            panel_issue_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_issue_cardLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton8)
                .addGap(70, 70, 70))
            .addGroup(panel_issue_cardLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(panel_issue_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_issue_cardLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_issue_cardLayout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(txt_customer_name, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_issue_cardLayout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(jButton7))
                    .addGroup(panel_issue_cardLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_issue_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_card_id, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_issue_cardLayout.createSequentialGroup()
                                .addComponent(txt_onlyno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(2, 2, 2)))))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        panel_issue_cardLayout.setVerticalGroup(
            panel_issue_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_issue_cardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_issue_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel_issue_cardLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(txt_customer_name)
                        .addGap(40, 40, 40))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panel_issue_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_amount, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addGap(14, 14, 14)
                .addComponent(txt_onlyno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_issue_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_card_id, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton7)
                .addGap(26, 26, 26)
                .addComponent(jButton8)
                .addGap(84, 84, 84))
        );

        jLayeredPane1.add(panel_issue_card, "card4");

        btn_back_add.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_back_add.setText("Back");
        btn_back_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_back_addActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Name");

        txt_fname.setToolTipText("");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Email");

        txt_email.setToolTipText("");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("National ID");

        txt_nic.setToolTipText("");

        btn_save.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_save.setText("Save");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Status");

        is_admin.setText("Is an administrator");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Passward");

        javax.swing.GroupLayout panel_addLayout = new javax.swing.GroupLayout(panel_add);
        panel_add.setLayout(panel_addLayout);
        panel_addLayout.setHorizontalGroup(
            panel_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_addLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(panel_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_addLayout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(is_admin)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panel_addLayout.createSequentialGroup()
                        .addComponent(btn_back_add)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 431, Short.MAX_VALUE)
                        .addComponent(btn_save)
                        .addGap(78, 78, 78))
                    .addGroup(panel_addLayout.createSequentialGroup()
                        .addGroup(panel_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_addLayout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_nic))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_addLayout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_pward))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_addLayout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_fname, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_lname, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_addLayout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_email)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panel_addLayout.setVerticalGroup(
            panel_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_addLayout.createSequentialGroup()
                .addGroup(panel_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_addLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(panel_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_fname, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)))
                    .addGroup(panel_addLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_lname, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pward, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nic, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(is_admin))
                .addGap(44, 44, 44)
                .addGroup(panel_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_back_add)
                    .addComponent(btn_save))
                .addGap(45, 45, 45))
        );

        jLayeredPane1.add(panel_add, "card6");

        btn_back_edit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_back_edit.setText("Back");
        btn_back_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_back_editActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Old Email");

        txt_oldemail.setToolTipText("");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("New Email");

        txt_newemail.setToolTipText("");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Confirm Email");

        txt_newemail1.setToolTipText("");

        btn_edit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_edit.setText("Save");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_edit_emailLayout = new javax.swing.GroupLayout(panel_edit_email);
        panel_edit_email.setLayout(panel_edit_emailLayout);
        panel_edit_emailLayout.setHorizontalGroup(
            panel_edit_emailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_edit_emailLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(btn_back_edit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_edit)
                .addGap(112, 112, 112))
            .addGroup(panel_edit_emailLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(panel_edit_emailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_edit_emailLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_oldemail, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_edit_emailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panel_edit_emailLayout.createSequentialGroup()
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_newemail, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panel_edit_emailLayout.createSequentialGroup()
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_newemail1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        panel_edit_emailLayout.setVerticalGroup(
            panel_edit_emailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_edit_emailLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(panel_edit_emailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_oldemail, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(panel_edit_emailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_newemail, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(panel_edit_emailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_newemail1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(panel_edit_emailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_back_edit)
                    .addComponent(btn_edit))
                .addGap(45, 45, 45))
        );

        jLayeredPane1.add(panel_edit_email, "card7");

        btn_back_search.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_back_search.setText("Back");
        btn_back_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_back_searchActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Email");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("National ID");

        btn_sear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_sear.setText("Search");
        btn_sear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Enter Email or Naional Card ID to Search:");

        btn_delete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        txt_search_result.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        javax.swing.GroupLayout panel_searchLayout = new javax.swing.GroupLayout(panel_search);
        panel_search.setLayout(panel_searchLayout);
        panel_searchLayout.setHorizontalGroup(
            panel_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_searchLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(btn_back_search)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 328, Short.MAX_VALUE)
                .addComponent(btn_delete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_sear)
                .addGap(74, 74, 74))
            .addGroup(panel_searchLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(panel_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addGroup(panel_searchLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(panel_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_search_result, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_searchLayout.createSequentialGroup()
                                .addGroup(panel_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(panel_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_mails)
                                    .addComponent(txt_nicno))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_searchLayout.setVerticalGroup(
            panel_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_searchLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel15)
                .addGap(50, 50, 50)
                .addGroup(panel_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_mails)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(panel_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_nicno)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addComponent(txt_search_result)
                .addGap(34, 34, 34)
                .addGroup(panel_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_back_search)
                    .addComponent(btn_sear)
                    .addComponent(btn_delete))
                .addGap(45, 45, 45))
        );

        jLayeredPane1.add(panel_search, "card5");

        btn_addcustomer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_addcustomer.setText("Add Customer");
        btn_addcustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addcustomerActionPerformed(evt);
            }
        });

        btn_issue.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_issue.setText("Issue  a Card");
        btn_issue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_issueActionPerformed(evt);
            }
        });

        btn_search.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_search.setText("Search a customer");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        jButton5.setText("jButton2");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_menuLayout = new javax.swing.GroupLayout(panel_menu);
        panel_menu.setLayout(panel_menuLayout);
        panel_menuLayout.setHorizontalGroup(
            panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_menuLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel_menuLayout.createSequentialGroup()
                        .addComponent(btn_issue, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_menuLayout.createSequentialGroup()
                        .addComponent(btn_addcustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        panel_menuLayout.setVerticalGroup(
            panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_menuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_addcustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_issue, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane1.add(panel_menu, "card3");

        btn_back_edit1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_back_edit1.setText("Back");
        btn_back_edit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_back_edit1ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Old Passward");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("New passward");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("New passward");

        btn_edit1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_edit1.setText("Save");
        btn_edit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_edit1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_edit_passwardLayout = new javax.swing.GroupLayout(panel_edit_passward);
        panel_edit_passward.setLayout(panel_edit_passwardLayout);
        panel_edit_passwardLayout.setHorizontalGroup(
            panel_edit_passwardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_edit_passwardLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(btn_back_edit1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 380, Short.MAX_VALUE)
                .addComponent(btn_edit1)
                .addGap(112, 112, 112))
            .addGroup(panel_edit_passwardLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(panel_edit_passwardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panel_edit_passwardLayout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_oldpassward, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_edit_passwardLayout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_newpassward))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_edit_passwardLayout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_newpassward1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_edit_passwardLayout.setVerticalGroup(
            panel_edit_passwardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_edit_passwardLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(panel_edit_passwardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_oldpassward, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(panel_edit_passwardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_newpassward, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(panel_edit_passwardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_newpassward1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(panel_edit_passwardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_back_edit1)
                    .addComponent(btn_edit1))
                .addGap(45, 45, 45))
        );

        jLayeredPane1.add(panel_edit_passward, "card7");

        jMenu1.setText("File");

        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jMenu1.add(logout);

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jMenu1.add(exit);

        jMenuBar1.add(jMenu1);

        Edit.setText("Edit");

        edit_email.setText("Change email");
        edit_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_emailActionPerformed(evt);
            }
        });
        Edit.add(edit_email);

        edit_passward.setText("Change passward");
        edit_passward.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_passwardActionPerformed(evt);
            }
        });
        Edit.add(edit_passward);

        jMenuBar1.add(Edit);

        Option.setText("Option");

        add_emp.setText("Add employer");
        add_emp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_empActionPerformed(evt);
            }
        });
        Option.add(add_emp);

        remove_emp.setText("Remove Emplyer");
        remove_emp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remove_empActionPerformed(evt);
            }
        });
        Option.add(remove_emp);

        search_emp.setText("Search Employer");
        search_emp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_empActionPerformed(evt);
            }
        });
        Option.add(search_emp);

        jMenuBar1.add(Option);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        if(login_success(token)){
            if(isadmin(token)){
                Option.setVisible(true);
            }
            Edit.setVisible(true);
            panel_login.setVisible(false);
            panel_menu.setVisible(false);
            panel_add.setVisible(false);
            panel_edit_email.setVisible(false);
            panel_search.setVisible(false);
            panel_issue_card.setVisible(true);
            panel_edit_passward.setVisible(false);
        }
    }//GEN-LAST:event_btn_loginActionPerformed

    private void btn_addcustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addcustomerActionPerformed
        panel_login.setVisible(false);
        panel_menu.setVisible(false);
        panel_add.setVisible(true);
        panel_edit_email.setVisible(false);
        panel_search.setVisible(false);
        panel_issue_card.setVisible(false);
        panel_edit_passward.setVisible(false);
    }//GEN-LAST:event_btn_addcustomerActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void btn_issueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_issueActionPerformed
        panel_login.setVisible(false);
        panel_menu.setVisible(false);
        panel_add.setVisible(false);
        panel_edit_email.setVisible(false);
        panel_search.setVisible(false);
        panel_issue_card.setVisible(true);
        panel_edit_passward.setVisible(false);
    }//GEN-LAST:event_btn_issueActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        panel_login.setVisible(false);
        panel_menu.setVisible(false);
        panel_add.setVisible(false);
        panel_edit_email.setVisible(false);
        panel_search.setVisible(true);
        panel_issue_card.setVisible(false);
        panel_edit_passward.setVisible(false);
    }//GEN-LAST:event_btn_searchActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        try{
            if(!(txt_amount.getText().equals("") || txt_customer_name.getText().equals("") || txt_card_id.getText().equals(""))){
                int i = Integer.parseInt(txt_amount.getText());
                JOptionPane.showMessageDialog(null, "Card Updated Succcessfully", "Message", JOptionPane.INFORMATION_MESSAGE);
                txt_amount.setText("");
                txt_customer_name.setText("");
                txt_card_id.setText("");
            }
        }catch(Exception e){
            
        }
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void btn_back_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_back_editActionPerformed
        panel_login.setVisible(false);
        panel_menu.setVisible(false);
        panel_add.setVisible(false);
        panel_edit_email.setVisible(false);
        panel_search.setVisible(false);
        panel_issue_card.setVisible(true);
        panel_edit_passward.setVisible(false);
    }//GEN-LAST:event_btn_back_editActionPerformed

    private void btn_back_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_back_searchActionPerformed
        panel_login.setVisible(false);
        panel_menu.setVisible(false);
        panel_add.setVisible(false);
        panel_edit_email.setVisible(false);
        panel_search.setVisible(false);
        panel_issue_card.setVisible(true);
        panel_edit_passward.setVisible(false);
    }//GEN-LAST:event_btn_back_searchActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        panel_login.setVisible(true);
        panel_menu.setVisible(false);
        panel_add.setVisible(false);
        panel_edit_email.setVisible(false);
        panel_search.setVisible(false);
        panel_issue_card.setVisible(false);
        panel_edit_passward.setVisible(false);
        email.setText("");
        pward.setText("");
        txt_error_login.setText("");
        token = "";
    }//GEN-LAST:event_logoutActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void edit_passwardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_passwardActionPerformed
        panel_login.setVisible(false);
        panel_menu.setVisible(false);
        panel_add.setVisible(false);
        panel_edit_email.setVisible(false);
        panel_search.setVisible(false);
        panel_issue_card.setVisible(false);
        panel_edit_passward.setVisible(true);
    }//GEN-LAST:event_edit_passwardActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        if(!(txt_oldemail.getText().equals("") || txt_newemail.getText().equals("") || txt_newemail1.getText().equals(""))){
            if(txt_oldemail.getText().equals(email.getText()) && txt_newemail.getText().equals(txt_newemail1.getText())){
                JOptionPane.showMessageDialog(null, "Passward updated successfully", "Message", JOptionPane.INFORMATION_MESSAGE);
                txt_oldemail.setText("");
                txt_newemail.setText("");
                txt_newemail1.setText("");
            }else{
                JOptionPane.showMessageDialog(null, "Passward does not match", "Message", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Could not accept empty data", "Message", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_searActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searActionPerformed
        if (txt_mails.getText().equals("madusha@gmail.com") || txt_mails.getText().equals("shanaka@gmail.com") || txt_nicno.getText().equals("973131559V")){
            txt_search_result.setText("There's an employer with reference to above details");
            btn_delete.setVisible(true);
        }
        
    }//GEN-LAST:event_btn_searActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {
            txt_card_id.setText("");
            Reader rdr = new Reader();
            //JSerialComm01 card = new JSerialComm01();
            //id = card.scan();
            txt_card_id.setText(rdr.test());
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void add_empActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_empActionPerformed
        panel_login.setVisible(false);
        panel_menu.setVisible(false);
        panel_add.setVisible(true);
        panel_edit_email.setVisible(false);
        panel_search.setVisible(false);
        panel_issue_card.setVisible(false); 
        panel_edit_passward.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_add_empActionPerformed

    private void remove_empActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remove_empActionPerformed
        panel_login.setVisible(false);
        panel_menu.setVisible(false);
        panel_add.setVisible(false);
        panel_edit_email.setVisible(false);
        panel_search.setVisible(true);
        panel_issue_card.setVisible(false);
        panel_edit_passward.setVisible(false);
    }//GEN-LAST:event_remove_empActionPerformed

    private void search_empActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_empActionPerformed
        panel_login.setVisible(false);
        panel_menu.setVisible(false);
        panel_add.setVisible(false);
        panel_edit_email.setVisible(false);
        panel_search.setVisible(true);
        panel_issue_card.setVisible(false);
        panel_edit_passward.setVisible(false);
    }//GEN-LAST:event_search_empActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        if(txt_fname.getText()==("") || txt_lname.getText()==("") || txt_email.getText().equals("") || txt_pward.getText().equals("") || txt_nic.getText().equals("")){
            JOptionPane.showMessageDialog(null, "You must fill all the informations", "Message", JOptionPane.ERROR_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(null, "Employer added Succcessfully", "Message", JOptionPane.INFORMATION_MESSAGE);
        }
        txt_lname.setText("");
        txt_fname.setText("");
        txt_email.setText("");
        txt_pward.setText("");
        txt_nic.setText("");
        is_admin.setSelected(false);
        
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_back_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_back_addActionPerformed
        panel_login.setVisible(false);
        panel_menu.setVisible(false);
        panel_add.setVisible(false);
        panel_edit_email.setVisible(false);
        panel_search.setVisible(false);
        panel_issue_card.setVisible(true);
        panel_edit_passward.setVisible(false);
    }//GEN-LAST:event_btn_back_addActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        JOptionPane.showMessageDialog(null, "Employer deleted successfully", "Message", JOptionPane.INFORMATION_MESSAGE);
        txt_nicno.setText("");
        txt_mails.setText("");
        txt_search_result.setText("");
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void txt_amountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_amountKeyPressed
        try{
            int i = Integer.parseInt(txt_amount.getText());
            txt_onlyno.setVisible(false);
        }catch(Exception e){
            txt_onlyno.setVisible(true);
        }
    }//GEN-LAST:event_txt_amountKeyPressed

    private void txt_amountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_amountKeyTyped
        
    }//GEN-LAST:event_txt_amountKeyTyped

    private void btn_back_edit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_back_edit1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_back_edit1ActionPerformed

    private void btn_edit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_edit1ActionPerformed
        if(!(txt_oldpassward.getText().equals("") || txt_newpassward.getText().equals("") || txt_newpassward1.getText().equals(""))){
            if(txt_oldpassward.getText().equals(pward.getText()) && txt_newpassward.getText().equals(txt_newpassward1.getText())){
                JOptionPane.showMessageDialog(null, "Passward updated successfully", "Message", JOptionPane.INFORMATION_MESSAGE);
                txt_oldpassward.setText("");
                txt_newpassward.setText("");
                txt_newpassward1.setText("");
            }else{
                JOptionPane.showMessageDialog(null, "Passward does not match", "Message", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Could not accept empty data", "Message", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_edit1ActionPerformed

    private void edit_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_emailActionPerformed
        panel_login.setVisible(false);
        panel_menu.setVisible(false);
        panel_add.setVisible(false);
        panel_edit_email.setVisible(true);
        panel_search.setVisible(false);
        panel_issue_card.setVisible(false);
        panel_edit_passward.setVisible(false);
    }//GEN-LAST:event_edit_emailActionPerformed

    public void setCardId(String str)
    {
        txt_card_id.setText(str);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Menu menu = new Menu();
                menu.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Edit;
    private javax.swing.JMenu Option;
    private javax.swing.JButton btn_addcustomer;
    private javax.swing.JButton btn_back_add;
    private javax.swing.JButton btn_back_edit;
    private javax.swing.JButton btn_back_edit1;
    private javax.swing.JButton btn_back_search;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_edit1;
    private javax.swing.JButton btn_issue;
    private javax.swing.JButton btn_login;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_sear;
    private javax.swing.JButton btn_search;
    private javax.swing.JMenuItem edit_email;
    private javax.swing.JMenuItem edit_passward;
    private javax.swing.JTextField email;
    private javax.swing.JMenuItem exit;
    private javax.swing.JCheckBox is_admin;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel panel_add;
    private javax.swing.JPanel panel_edit_email;
    private javax.swing.JPanel panel_edit_passward;
    private javax.swing.JPanel panel_issue_card;
    private javax.swing.JPanel panel_login;
    private javax.swing.JPanel panel_menu;
    private javax.swing.JPanel panel_search;
    private javax.swing.JPasswordField pward;
    private javax.swing.JMenuItem remove_emp;
    private javax.swing.JMenuItem search_emp;
    private javax.swing.JTextField txt_amount;
    private javax.swing.JTextField txt_card_id;
    private javax.swing.JTextField txt_customer_name;
    private javax.swing.JTextField txt_email;
    private javax.swing.JLabel txt_error_login;
    private javax.swing.JTextField txt_fname;
    private javax.swing.JTextField txt_lname;
    private javax.swing.JTextField txt_mails;
    private javax.swing.JTextField txt_newemail;
    private javax.swing.JTextField txt_newemail1;
    private javax.swing.JPasswordField txt_newpassward;
    private javax.swing.JPasswordField txt_newpassward1;
    private javax.swing.JTextField txt_nic;
    private javax.swing.JTextField txt_nicno;
    private javax.swing.JTextField txt_oldemail;
    private javax.swing.JPasswordField txt_oldpassward;
    private javax.swing.JLabel txt_onlyno;
    private javax.swing.JPasswordField txt_pward;
    private javax.swing.JLabel txt_search_result;
    // End of variables declaration//GEN-END:variables
}
